Repository jitsi/jitsi, pull requests merged in 2018-09, with the labels that each got.

#528 Fix video reinit when putting a call on hold
  src/net/java/sip/communicator/impl/neomedia/MediaConfigurationImpl.java
  src/net/java/sip/communicator/service/protocol/media/CallPeerMediaHandler.java
Labels: component:Call, component:UI, type:bug

#472 Fix the issue with IP-address in uri for the xmpp call from a command line
  src/net/java/sip/communicator/impl/protocol/jabber/UriHandlerJabberImpl.java
Labels: type:bug

#532 Mac command / Win key translations
  src/net/java/sip/communicator/impl/hid/HIDServiceImpl.java
Labels: component:Desktop-Sharing, platform:Mac, platform:Windows
